"""Dev-preview rasteriser for the pentaglyph two-axis taxonomy matrix.

Renders a Pillow-based preview from the layout described in
[`layers-matrix.txt`](./layers-matrix.txt) — 6 concern rows
(⓪ Standards ... ⑤ Measurement) × 3 change-rate columns (A Durable /
B Volatile / C Frozen), with the cell-by-cell content table embedded
directly in this script so the spec file remains the canonical source
for `paperbanana`.

Why this script exists
----------------------
The production `layers-matrix.png` (~6.5 MB, committed to the repo) is
generated by `paperbanana` (Gemini 3 Pro Image Preview) feeding from
`layers-matrix.txt`. That pipeline requires `gcloud auth` + the
Accenture GCP tenant + the `paperbanana` CLI installed locally, which
not every developer environment can satisfy.

This script provides a **gcloud-free, dependency-light dev preview**
that any contributor can run from the backend `uv` venv (Pillow 12.2
is already a transitive dep) to:

* Sanity-check that a `layers-matrix.txt` revision still composes into
  a coherent 3×6 figure before paying for a Gemini round-trip.
* Produce a screen-readable PNG when working offline.
* Keep the cell-by-cell taxonomy content in version control as Python
  literals so reviewers can `git diff` taxonomy changes precisely.

The script **deliberately writes a different filename** —
`layers-matrix-dev-preview.png` — so it never overwrites the canonical
paperbanana raster (`layers-matrix.png`). A `--overwrite-canonical`
flag is intentionally not provided.

Run
---

    /workspace/backend/.venv/bin/python \\
        libs/pentaglyph-docs/assets/_build_layers_matrix.py

Linked to AB#2018 (preflight-feature-gate hook の周辺整備,
AB#1989 follow-up).
"""

from __future__ import annotations

from PIL import Image, ImageDraw, ImageFont
from pathlib import Path

# ── Canvas + layout (mirrors layers-matrix.txt §「全体レイアウト」) ────────
W, H = 3584, 2048
BG = (247, 248, 250)  # #F7F8FA
INK = (17, 24, 39)  # #111827
INK_MUTED = (75, 85, 99)  # #4B5563
INK_SUBTLE = (107, 114, 128)  # #6B7280
INK_LINE = (229, 231, 235)  # #E5E7EB
INK_DISABLED = (209, 213, 219)  # #D1D5DB
INK_PLACEHOLDER = (156, 163, 175)  # #9CA3AF
CELL_TEXT = (31, 41, 55)  # #1F2937

TOP_BAND = (0, 245)
MATRIX_BAND = (245, 1885)
BOTTOM_BAND = (1885, H)

ROW_HEADER_W = 480
COL_HEADER_H = 180

# Concern axis rows (top → bottom in reading order).
# Colour bar HEX matches layers.png for cross-figure consistency.
ROWS = [
    ("⓪", "Standards", "標準", (31, 111, 235)),
    ("①", "Artefacts", "成果物", (11, 138, 58)),
    ("②", "Process", "プロセス", (180, 83, 9)),
    ("③", "Automation", "自動化", (107, 70, 193)),
    ("④", "Governance", "ガバナンス", (190, 24, 93)),
    ("⑤", "Measurement", "計測 (optional)", (75, 85, 99)),
]

# Change-rate axis columns (left → right).
COLS = [
    ("Layer A — Durable design", "Slow change · reviewed before merge", (17, 24, 39), (255, 255, 255)),
    ("Layer B — Volatile working material", "Dated · append-only · latest-wins", (107, 114, 128), (255, 255, 255)),
    ("Layer C — Reference and archive", "Frozen · read-only", (209, 213, 219), (17, 24, 39)),
]

# Cells indexed [row][col]. Each entry is a list of body lines, or the
# sentinel "EMPTY" which renders an em-dash + intentionally-empty note.
EMPTY = "EMPTY"
CELLS: list[list[object]] = [
    # ⓪ Standards
    [
        ["STRATEGY.md §2", "(no directory)"],
        EMPTY,
        EMPTY,
    ],
    # ① Artefacts
    [
        [
            "01-artefacts/templates/",
            "01-artefacts/arc42/",
            "01-artefacts/detailed-design/",
            "01-artefacts/api-contract/",
            "01-artefacts/user-manual/",
            "01-artefacts/diagrams/c4/",
        ],
        ["client-engagement/", "{reports,daci,kickoffs}/"],
        ["archive/_legacy/"],
    ],
    # ② Process
    [
        [
            "02-process/version-control.md",
            "02-process/dev-cycle.md",
            "02-process/dod-dor.md",
            "02-process/tdd-workflow.md",
            "02-process/bdd-workflow.md",
        ],
        [
            "01-artefacts/impl-plans/",
            "01-artefacts/postmortems/",
            "01-artefacts/reports/",
        ],
        EMPTY,
    ],
    # ③ Automation
    [
        ["cli/", ".claude/", "scripts/docs/"],
        EMPTY,
        EMPTY,
    ],
    # ④ Governance
    [
        [
            "04-governance/raci.md",
            "04-governance/adr-accept-protocol.md",
            "04-governance/override-justification.md",
            "04-governance/contributing.md",
        ],
        ["01-artefacts/cost-estimates/"],
        EMPTY,
    ],
    # ⑤ Measurement (rendered at 80% opacity)
    [
        ["05-measurement/README.md", "05-measurement/baseline.md"],
        ["05-measurement/snapshots/", "YYYY-MM-DD_*.md"],
        EMPTY,
    ],
]


def _load_font(size: int, *, bold: bool = False, mono: bool = False) -> ImageFont.FreeTypeFont:
    """Best-effort font load; falls back to PIL default if no candidate exists.

    Prefers Noto Sans CJK so Japanese sub-labels (`標準`, `成果物`, ...)
    render correctly. DejaVu Sans is the ASCII fallback when CJK fonts
    are unavailable.
    """
    if mono:
        candidates = [
            "/usr/share/fonts/truetype/noto/NotoSansMono-Regular.ttf",
            "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf",
        ]
    elif bold:
        candidates = [
            "/usr/share/fonts/opentype/noto/NotoSansCJK-Bold.ttc",
            "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
        ]
    else:
        candidates = [
            "/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc",
            "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
        ]
    for path in candidates:
        if Path(path).exists():
            return ImageFont.truetype(path, size)
    return ImageFont.load_default()


def _draw_empty_cell(draw: ImageDraw.ImageDraw, cx: float, cy: float, opacity: float) -> None:
    """Render an em-dash + `intentionally empty` note for blank cells."""
    dash_font = _load_font(64, bold=True)
    note_font = _load_font(20)
    em = "—"
    note = "intentionally empty"
    dw = draw.textlength(em, font=dash_font)
    nw = draw.textlength(note, font=note_font)
    dash_colour = tuple(int(c * opacity + 255 * (1 - opacity)) for c in INK_DISABLED)
    note_colour = tuple(int(c * opacity + 255 * (1 - opacity)) for c in INK_PLACEHOLDER)
    draw.text((cx - dw / 2, cy - 50), em, fill=dash_colour, font=dash_font)
    draw.text((cx - nw / 2, cy + 20), note, fill=note_colour, font=note_font)


def _draw_path_cell(
    draw: ImageDraw.ImageDraw,
    x0: float,
    y0: float,
    cw: float,
    ch: float,
    lines: list[str],
    opacity: float,
) -> None:
    """Render a multi-line list of paths inside a cell."""
    font = _load_font(20, mono=True)
    line_h = 28
    total_h = line_h * len(lines)
    start_y = y0 + (ch - total_h) / 2
    ink = tuple(int(c * opacity + 255 * (1 - opacity)) for c in CELL_TEXT)
    for i, line in enumerate(lines):
        text = line
        while draw.textlength(text, font=font) > cw - 24 and len(text) > 10:
            text = text[:-2] + "…"
        tw = draw.textlength(text, font=font)
        draw.text((x0 + (cw - tw) / 2, start_y + i * line_h), text, fill=ink, font=font)


def render() -> Path:
    img = Image.new("RGB", (W, H), BG)
    draw = ImageDraw.Draw(img)

    # ── TOP BAND ───────────────────────────────────────────────
    title_font = _load_font(108, bold=True)
    subtitle_font = _load_font(34)
    title = "pentaglyph two-axis taxonomy"
    subtitle = "concern (⓪–⑤) × change-rate (A/B/C) — dev preview"
    tw = draw.textlength(title, font=title_font)
    sw = draw.textlength(subtitle, font=subtitle_font)
    draw.text(((W - tw) / 2, 40), title, fill=INK, font=title_font)
    draw.text(((W - sw) / 2, 170), subtitle, fill=INK_MUTED, font=subtitle_font)

    # ── MATRIX BAND geometry ───────────────────────────────────
    matrix_top = MATRIX_BAND[0]
    matrix_bottom = MATRIX_BAND[1]
    body_top = matrix_top + COL_HEADER_H
    body_left = ROW_HEADER_W
    body_w = W - body_left
    body_h = matrix_bottom - body_top
    cell_w = body_w / 3
    cell_h = body_h / 6

    # Column headers (pill backgrounds, no accent colours).
    col_title_font = _load_font(34, bold=True)
    col_sub_font = _load_font(20)
    pill_pad_y = 18
    pill_radius = 24
    for i, (title_, sub_, bg, fg) in enumerate(COLS):
        cx_left = body_left + cell_w * i
        cx_center = cx_left + cell_w / 2
        pill_left = cx_left + 30
        pill_right = cx_left + cell_w - 30
        pill_top = matrix_top + 22
        pill_bot = pill_top + 70
        draw.rounded_rectangle(
            [(pill_left, pill_top), (pill_right, pill_bot)],
            radius=pill_radius,
            fill=bg,
        )
        tw_ = draw.textlength(title_, font=col_title_font)
        draw.text(
            (cx_center - tw_ / 2, pill_top + pill_pad_y - 2),
            title_,
            fill=fg,
            font=col_title_font,
        )
        sw_ = draw.textlength(sub_, font=col_sub_font)
        draw.text(
            (cx_center - sw_ / 2, pill_bot + 14),
            sub_,
            fill=INK_SUBTLE,
            font=col_sub_font,
        )
        if i > 0:
            x = body_left + cell_w * i
            draw.line([(x, body_top), (x, matrix_bottom)], fill=INK_LINE, width=1)

    # Body top divider.
    draw.line([(body_left, body_top), (W, body_top)], fill=INK_LINE, width=1)

    # Row headers + cells.
    row_label_font = _load_font(36, bold=True)
    row_sub_font = _load_font(22)
    for r, (num, en, jp, color) in enumerate(ROWS):
        y0 = body_top + cell_h * r
        opacity = 0.8 if r == 5 else 1.0  # ⑤ Measurement is dimmed.

        # Coloured bar.
        draw.rectangle([(0, y0), (12, y0 + cell_h)], fill=color)
        # Label.
        label = f"{num} {en}"
        label_colour = tuple(int(c * opacity + 255 * (1 - opacity)) for c in INK)
        sub_colour = tuple(int(c * opacity + 255 * (1 - opacity)) for c in INK_SUBTLE)
        draw.text((40, y0 + 50), label, fill=label_colour, font=row_label_font)
        draw.text((40, y0 + 105), jp, fill=sub_colour, font=row_sub_font)

        # Row separator above.
        if r > 0:
            draw.line([(0, y0), (W, y0)], fill=INK_LINE, width=1)

        # Cells in this row.
        for c, content in enumerate(CELLS[r]):
            x0 = body_left + cell_w * c
            cx_center = x0 + cell_w / 2
            cy_center = y0 + cell_h / 2
            if content == EMPTY:
                _draw_empty_cell(draw, cx_center, cy_center, opacity)
            else:
                _draw_path_cell(draw, x0, y0, cell_w, cell_h, content, opacity)

    # Outer frame.
    draw.rectangle(
        [(body_left, body_top), (W - 1, matrix_bottom - 1)],
        outline=INK_LINE,
        width=1,
    )

    # ── BOTTOM BAND ────────────────────────────────────────────
    caption_font = _load_font(26)
    caption = "Place by concern first (⓪–⑤). Then pick change-rate (A/B/C). Empty cells signal a misclassification."
    cw_ = draw.textlength(caption, font=caption_font)
    band_mid_y = (BOTTOM_BAND[0] + BOTTOM_BAND[1]) / 2 - 13
    draw.text(((W - cw_) / 2, band_mid_y), caption, fill=INK_SUBTLE, font=caption_font)

    out = Path(__file__).resolve().parent / "layers-matrix-dev-preview.png"
    img.save(out, format="PNG")
    return out


if __name__ == "__main__":
    p = render()
    print(f"wrote {p} ({p.stat().st_size} bytes)")
